"""Small localization helper for UI text."""

from __future__ import annotations

TRANSLATIONS = {
    "zh": {
        "lang_name": "中文",
        "startup_title": "Snake Legends",
        "startup_subtitle": "请选择界面语言",
        "startup_confirm": "按 Enter 或空格确认",
        "startup_hint": "左右方向键切换语言",
        "menu_title": "Snake Legends",
        "chip_arcade": "策略街机",
        "modes_title": "模式选择",
        "briefing_title": "当前模式",
        "briefing_1": "撞墙或撞到自己的尾巴会立刻结束本局。",
        "briefing_2": "蛇身越长，移动速度越快。",
        "briefing_3": "每个模式都支持直接开始或 AI 演示。",
        "briefing_4": "局域网模式请先由一台设备开房，另一台设备通过 LAN Join 加入。",
        "footer_1": "Enter / 空格：进入设置",
        "footer_2": "上下方向键：切换模式",
        "footer_3": "左右方向键：切换难度",
        "setup_title": "开始设置",
        "setup_action": "运行方式",
        "setup_action_play": "直接开始",
        "setup_action_demo": "AI 演示",
        "setup_hours": "小时",
        "setup_minutes": "分钟",
        "setup_seconds": "秒",
        "setup_confirm": "开始游戏",
        "setup_hint_1": "上下切换项目，左右调整数值",
        "setup_hint_2": "Enter 确认，Esc 返回",
        "setup_guide_title": "玩法说明",
        "setup_guide_timed_solo": "单人冲分模式，方向键控制，适合练手和刷分。",
        "setup_guide_versus_ai": "你和 AI 同场争夺食物与空间，拼路线也拼节奏。",
        "setup_guide_local_duel": "本地双人对战，玩家一用方向键，玩家二用 WASD。",
        "setup_guide_coop": "双人合作模式，互相配合在时间结束前拿到更高团队分。",
        "setup_guide_lan_host": "创建局域网房间，等待另一台设备加入后开始对战。",
        "setup_guide_rhythm_mode": "节奏模式会让移动与刷新跟随节拍，并显示连击信息。",
        "setup_guide_strategy_mode": "策略模式会加入技能点、随机事件和更偏战术的 AI。",
        "join_title": "加入局域网房间",
        "join_desc": "输入主机 IPv4 地址，或从下方自动发现列表中选择房间。",
        "join_tip_1": "默认端口：{port}",
        "join_tip_2": "Backspace 删除，Enter 连接",
        "join_tip_3": "Esc 返回菜单",
        "join_tip_4": "上下选择房间，Tab 自动填入 IP",
        "host_title": "局域网大厅",
        "host_waiting": "等待另一位玩家加入",
        "share_ip": "主机 IP",
        "share_code": "房间码",
        "host_note_1": "请确认端口 {port} 在局域网内可访问。",
        "host_note_2": "远端加入后会自动开始对局。",
        "host_note_3": "按 R 重新开房，按 Esc 取消。",
        "client_connected": "已连接主机",
        "client_waiting": "等待主机开始并同步首帧画面。",
        "remote_title": "远端控制",
        "remote_1": "你正在控制第二条蛇。",
        "remote_2": "使用方向键发送移动输入。",
        "remote_3": "按 Esc 断开连接并返回菜单。",
        "sidebar_title": "对局状态",
        "intel_title": "战况提示",
        "career_title": "生涯统计",
        "games_played": "总局数 {value}",
        "high_score": "最高分 {value}",
        "food_eaten": "吃到食物 {value}",
        "best_mode": "本模式最佳 {value}",
        "tip_pause": "P 暂停",
        "tip_restart": "R 重开",
        "tip_menu": "M 菜单",
        "tip_ai": "Tab 显示 AI 路径",
        "discovery_title": "自动发现",
        "discovery_empty": "暂未发现房间",
        "discovery_pick": "可直接选择下方房间",
        "paused": "已暂停",
        "paused_1": "按 P 继续，立即恢复对局",
        "paused_2": "按 R 可随时重开当前模式",
        "paused_3": "按 M 或 Esc 可随时返回菜单",
        "score_label": "分数 {value}",
        "timer_label": "时间 {value}",
        "speed_label": "速度 {value}",
        "difficulty_easy_label": "简单",
        "difficulty_normal_label": "普通",
        "difficulty_hard_label": "困难",
        "difficulty_value": "难度 {value}",
        "badge_ai": "AI",
        "badge_phase": "穿越 {value}",
        "badge_slow": "减速 {value}",
        "badge_haste": "加速 {value}",
        "badge_bounce": "反弹 {value}",
        "badge_magnet": "磁吸 {value}",
        "badge_out": "出局",
        "food_apple": "苹果",
        "food_gold": "黄金果",
        "food_phase": "穿越果",
        "food_freeze": "冻结果",
        "food_haste": "疾速果",
        "food_bounce": "反弹果",
        "food_magnet": "磁吸果",
        "mode_timed_solo_label": "限时单人",
        "mode_timed_solo_desc": "可自定义时长的单人冲分模式。",
        "mode_versus_ai_label": "人机对战",
        "mode_versus_ai_desc": "和 AI 抢食物、争路线、比生存。",
        "mode_local_duel_label": "本地对决",
        "mode_local_duel_desc": "同一键盘双人对战，方向键对 WASD。",
        "mode_coop_label": "双人合作",
        "mode_coop_desc": "两名玩家合作冲击团队目标分数。",
        "mode_lan_host_label": "局域网开房",
        "mode_lan_host_desc": "创建局域网房间并等待远端加入。",
        "mode_lan_join_label": "局域网加入",
        "mode_lan_join_desc": "输入 IP 或从自动发现列表加入房间。",
        "mode_lan_duel_label": "局域网对战",
        "mode_rhythm_mode_label": "节奏模式",
        "mode_rhythm_mode_desc": "蛇移动和食物刷新跟随音乐节拍，并统计连击。",
        "mode_strategy_mode_label": "策略模式",
        "mode_strategy_mode_desc": "加入技能点、随机事件和战术 AI 的进阶模式。",
        "msg_choose_mode": "选择一个模式并进入设置。",
        "msg_collect": "吃食物、避开墙体，也不要咬到自己。",
        "msg_hosting": "房间已创建：{ip}:{port}",
        "msg_host_failed": "开房失败：{error}",
        "msg_join_input": "请输入主机 IPv4 地址，或选择自动发现的房间。",
        "msg_connected_wait": "连接成功，等待主机开始。",
        "msg_connect_failed": "连接失败：{error}",
        "msg_paused": "游戏已暂停。",
        "msg_resume": "继续游戏。",
        "msg_remote_lost": "远端连接已断开，已返回菜单。",
        "msg_remote_joined": "远端玩家已加入，对局开始。",
        "msg_disconnected": "已与主机断开，按 Esc 返回。",
        "msg_food_captured": "{name} 吃到了 {food}。",
        "msg_haste_used": "{name} 获得了加速效果。",
        "msg_freeze_used": "{name} 触发了减速效果。",
        "msg_bounce_ready": "{name} 获得了反弹墙效果。",
        "msg_bounce_used": "{name} 触发了反弹墙。",
        "msg_magnet_used": "{name} 获得了磁吸效果。",
        "msg_magnet_pull": "{name} 用磁吸拉到了 {food}。",
        "msg_food_vanished": "{food} 已消失。",
        "msg_obstacles": "地图中出现了新的障碍。",
        "game_over": "游戏结束",
        "game_over_score": "最终分数：{score}",
        "retry_hint": "按 Enter 或空格再来一局。",
        "menu_hint": "按 M 返回菜单。",
        "mission_cleared": "合作成功",
        "mission_score": "团队分数达到 {score}。",
        "mission_team": "本局合作完成。",
        "mission_failed": "合作失败",
        "mission_failed_score": "团队分数：{score}",
        "mission_failed_tip": "试试更好的走位配合和节奏分配。",
        "winner_title": "{name} 获胜",
        "winner_score": "{name} 以 {score} 分结束比赛。",
        "opponent_score": "对手分数：{score}",
        "restart_mode": "按 Enter 或空格重新开始。",
        "result_reason": "原因：{reason}",
        "reason_wall": "撞到墙体",
        "reason_obstacle": "撞到障碍物",
        "reason_self": "咬到了自己的尾巴",
        "reason_head_on": "与对手正面相撞",
        "reason_other": "撞到了 {name}",
        "reason_score_target": "率先达到目标分数",
        "reason_last_alive": "成为最后存活的蛇",
        "reason_timer_end": "倒计时结束",
        "reason_team_failed": "团队在时限内未完成目标",
        "result_play_again": "继续游戏",
        "result_change_mode": "更换模式",
        "result_quit": "退出游戏",
    },
    "en": {
        "lang_name": "English",
        "startup_title": "Snake Legends",
        "startup_subtitle": "Choose your interface language.",
        "startup_confirm": "Press Enter or Space",
        "startup_hint": "Use Left / Right to switch language",
        "menu_title": "Snake Legends",
        "chip_arcade": "Arcade",
        "modes_title": "Modes",
        "briefing_title": "Selected Mode",
        "briefing_1": "Hitting a wall or your own tail ends the round.",
        "briefing_2": "The snake gets faster as it grows longer.",
        "briefing_3": "Every mode offers Start Game or AI Demo.",
        "briefing_4": "Use LAN Host to create a room and LAN Join to connect.",
        "footer_1": "Enter / Space opens setup",
        "footer_2": "Up / Down switches modes",
        "footer_3": "Left / Right changes difficulty",
        "setup_title": "Start Options",
        "setup_action": "Run Type",
        "setup_action_play": "Start Game",
        "setup_action_demo": "AI Demo",
        "setup_hours": "Hours",
        "setup_minutes": "Minutes",
        "setup_seconds": "Seconds",
        "setup_confirm": "Launch",
        "setup_hint_1": "Up / Down selects, Left / Right adjusts",
        "setup_hint_2": "Enter confirms, Esc returns",
        "setup_guide_title": "Guide",
        "setup_guide_timed_solo": "Single-snake score attack with Arrow Keys.",
        "setup_guide_versus_ai": "Race an AI rival for food and control.",
        "setup_guide_local_duel": "Player one uses Arrow Keys, player two uses WASD.",
        "setup_guide_coop": "Two local players cooperate to score within the timer.",
        "setup_guide_lan_host": "Host first, then let another machine join via LAN Join.",
        "setup_guide_rhythm_mode": "A beat-driven mode with combo HUD and music timing.",
        "setup_guide_strategy_mode": "A tactical mode with skill points, events, and AI roles.",
        "join_title": "Join LAN Room",
        "join_desc": "Enter the host IPv4 address or pick a discovered room below.",
        "join_tip_1": "Default port: {port}",
        "join_tip_2": "Backspace deletes, Enter connects",
        "join_tip_3": "Esc returns to menu",
        "join_tip_4": "Use Up / Down to choose a room, Tab copies its IP",
        "host_title": "LAN Lobby",
        "host_waiting": "Waiting for another player",
        "share_ip": "Host IP",
        "share_code": "Room Code",
        "host_note_1": "Make sure port {port} is reachable on your LAN.",
        "host_note_2": "The match starts as soon as the client joins.",
        "host_note_3": "Press R to reopen or Esc to cancel.",
        "client_connected": "Connected To Host",
        "client_waiting": "Waiting for the host to begin and stream the first frame.",
        "remote_title": "Remote Control",
        "remote_1": "You are controlling the second snake.",
        "remote_2": "Use Arrow Keys to send inputs.",
        "remote_3": "Press Esc to disconnect.",
        "sidebar_title": "Status",
        "intel_title": "Round Intel",
        "career_title": "Career Stats",
        "games_played": "Games played {value}",
        "high_score": "High score {value}",
        "food_eaten": "Food eaten {value}",
        "best_mode": "Best in mode {value}",
        "tip_pause": "P pause",
        "tip_restart": "R restart",
        "tip_menu": "M menu",
        "tip_ai": "Tab AI path",
        "discovery_title": "Auto Discovery",
        "discovery_empty": "No rooms found yet",
        "discovery_pick": "You can choose a room below",
        "paused": "Paused",
        "paused_1": "Press P to continue immediately",
        "paused_2": "Press R anytime to restart this mode",
        "paused_3": "Press M or Esc anytime to return",
        "score_label": "Score {value}",
        "timer_label": "Time {value}",
        "speed_label": "Speed {value}",
        "difficulty_easy_label": "Simple",
        "difficulty_normal_label": "Normal",
        "difficulty_hard_label": "Hard",
        "difficulty_value": "Difficulty {value}",
        "badge_ai": "AI",
        "badge_phase": "Phase {value}",
        "badge_slow": "Slow {value}",
        "badge_haste": "Haste {value}",
        "badge_bounce": "Bounce {value}",
        "badge_magnet": "Magnet {value}",
        "badge_out": "Out",
        "food_apple": "Apple",
        "food_gold": "Gold Fruit",
        "food_phase": "Phase Fruit",
        "food_freeze": "Freeze Fruit",
        "food_haste": "Haste Fruit",
        "food_bounce": "Bounce Fruit",
        "food_magnet": "Magnet Fruit",
        "mode_timed_solo_label": "Timed Solo",
        "mode_timed_solo_desc": "A solo score mode with editable match time.",
        "mode_versus_ai_label": "Human Vs AI",
        "mode_versus_ai_desc": "Compete against an AI opponent.",
        "mode_local_duel_label": "Local Duel",
        "mode_local_duel_desc": "Two-player local duel on one keyboard.",
        "mode_coop_label": "Co-op Run",
        "mode_coop_desc": "Two-player local co-op under a shared timer.",
        "mode_lan_host_label": "LAN Host",
        "mode_lan_host_desc": "Create a LAN room and wait for a remote player.",
        "mode_lan_join_label": "LAN Join",
        "mode_lan_join_desc": "Join a LAN room by IP or discovery.",
        "mode_lan_duel_label": "LAN Duel",
        "mode_rhythm_mode_label": "Rhythm Mode",
        "mode_rhythm_mode_desc": "Sync snake movement to the beat and chase combos.",
        "mode_strategy_mode_label": "Strategy Mode",
        "mode_strategy_mode_desc": "Play with skill points, events, and tactical AI pressure.",
        "msg_choose_mode": "Choose a mode and open its setup.",
        "msg_collect": "Collect food and avoid walls and your own tail.",
        "msg_hosting": "Room created on {ip}:{port}",
        "msg_host_failed": "Host failed: {error}",
        "msg_join_input": "Enter the host IPv4 address or pick a discovered room.",
        "msg_connected_wait": "Connected. Waiting for the host to start.",
        "msg_connect_failed": "Connection failed: {error}",
        "msg_paused": "Paused.",
        "msg_resume": "Back in action.",
        "msg_remote_lost": "Remote connection lost. Returning to menu.",
        "msg_remote_joined": "Remote player joined. Match started.",
        "msg_disconnected": "Disconnected from host. Press Esc to return.",
        "msg_food_captured": "{name} captured {food}.",
        "msg_haste_used": "{name} gained haste.",
        "msg_freeze_used": "{name} slowed the field.",
        "msg_bounce_ready": "{name} can now bounce off walls.",
        "msg_bounce_used": "{name} bounced off a wall.",
        "msg_magnet_used": "{name} gained magnet pull.",
        "msg_magnet_pull": "{name} pulled in {food} with magnet.",
        "msg_food_vanished": "{food} vanished.",
        "msg_obstacles": "New obstacles have appeared.",
        "game_over": "Game Over",
        "game_over_score": "Final score: {score}",
        "retry_hint": "Press Enter or Space to play again.",
        "menu_hint": "Press M for menu.",
        "mission_cleared": "Mission Cleared",
        "mission_score": "Team score reached {score}.",
        "mission_team": "The co-op run is complete.",
        "mission_failed": "Mission Failed",
        "mission_failed_score": "Team score: {score}",
        "mission_failed_tip": "Try better route timing and coordination.",
        "winner_title": "{name} Wins",
        "winner_score": "{name} finished with {score} points.",
        "opponent_score": "Opponent score: {score}",
        "restart_mode": "Press Enter or Space to restart.",
        "result_reason": "Reason: {reason}",
        "reason_wall": "Hit a wall",
        "reason_obstacle": "Hit an obstacle",
        "reason_self": "Bit its own tail",
        "reason_head_on": "Head-on collision",
        "reason_other": "Collided with {name}",
        "reason_score_target": "Reached the target score first",
        "reason_last_alive": "Became the last surviving snake",
        "reason_timer_end": "Timer ran out",
        "reason_team_failed": "The team missed the objective before time ran out",
        "result_play_again": "Play Again",
        "result_change_mode": "Change Mode",
        "result_quit": "Quit Game",
    },
    "de": {
        "lang_name": "Deutsch",
        "startup_title": "Snake Legends",
        "startup_subtitle": "Waehle deine Sprache.",
        "startup_confirm": "Enter oder Leertaste",
        "startup_hint": "Mit Links / Rechts Sprache wechseln",
        "menu_title": "Snake Legends",
        "chip_arcade": "Arcade",
        "modes_title": "Modi",
        "briefing_title": "Aktiver Modus",
        "briefing_1": "Wand oder eigener Schwanz beendet die Runde.",
        "briefing_2": "Mit mehr Laenge steigt die Geschwindigkeit.",
        "briefing_3": "Jeder Modus bietet Direktstart oder KI-Demo.",
        "briefing_4": "LAN Host erstellt einen Raum, LAN Join verbindet sich.",
        "footer_1": "Enter / Leertaste oeffnet die Einstellungen",
        "footer_2": "Hoch / Runter wechselt Modi",
        "footer_3": "Links / Rechts aendert die Schwierigkeit",
        "setup_title": "Startoptionen",
        "setup_action": "Ablauf",
        "setup_action_play": "Direkt starten",
        "setup_action_demo": "KI-Demo",
        "setup_hours": "Stunden",
        "setup_minutes": "Minuten",
        "setup_seconds": "Sekunden",
        "setup_confirm": "Starten",
        "setup_hint_1": "Hoch / Runter waehlt, Links / Rechts aendert",
        "setup_hint_2": "Enter bestaetigt, Esc kehrt zurueck",
        "setup_guide_title": "Hinweis",
        "setup_guide_timed_solo": "Einzelmodus mit Pfeiltasten und Zeitvorgabe.",
        "setup_guide_versus_ai": "Spiele gegen eine KI um Futter und Raum.",
        "setup_guide_local_duel": "Spieler eins nutzt Pfeile, Spieler zwei nutzt WASD.",
        "setup_guide_coop": "Zwei lokale Spieler sammeln gemeinsam Punkte vor Ablauf der Zeit.",
        "setup_guide_lan_host": "Erst hosten, dann ueber LAN Join vom zweiten Rechner beitreten.",
        "setup_guide_rhythm_mode": "Beat-gesteuerter Modus mit Combo-HUD und Musiktempo.",
        "setup_guide_strategy_mode": "Taktikmodus mit Skillpunkten, Events und KI-Rollen.",
        "join_title": "LAN-Raum beitreten",
        "join_desc": "Host-IP eingeben oder einen gefundenen Raum auswaehlen.",
        "join_tip_1": "Standard-Port: {port}",
        "join_tip_2": "Backspace loescht, Enter verbindet",
        "join_tip_3": "Esc zurueck ins Menue",
        "join_tip_4": "Mit Hoch / Runter waehlen, Tab uebernimmt die IP",
        "host_title": "LAN-Lobby",
        "host_waiting": "Warte auf einen weiteren Spieler",
        "share_ip": "Host-IP",
        "share_code": "Raumcode",
        "host_note_1": "Port {port} muss im LAN erreichbar sein.",
        "host_note_2": "Das Match startet automatisch nach dem Beitritt.",
        "host_note_3": "R erstellt neu, Esc bricht ab.",
        "client_connected": "Mit Host verbunden",
        "client_waiting": "Warten auf den Start und das erste Bild vom Host.",
        "remote_title": "Fernsteuerung",
        "remote_1": "Du steuerst die zweite Schlange.",
        "remote_2": "Mit Pfeiltasten werden Eingaben gesendet.",
        "remote_3": "Esc trennt die Verbindung.",
        "sidebar_title": "Status",
        "intel_title": "Rundeninfo",
        "career_title": "Statistik",
        "games_played": "Spiele {value}",
        "high_score": "Rekord {value}",
        "food_eaten": "Gefressen {value}",
        "best_mode": "Bester Modus {value}",
        "tip_pause": "P Pause",
        "tip_restart": "R Neustart",
        "tip_menu": "M Menue",
        "tip_ai": "Tab KI-Pfad",
        "discovery_title": "Auto-Erkennung",
        "discovery_empty": "Noch keine Raeume gefunden",
        "discovery_pick": "Du kannst unten einen Raum waehlen",
        "paused": "Pausiert",
        "paused_1": "Mit P sofort fortsetzen",
        "paused_2": "Mit R den Modus jederzeit neu starten",
        "paused_3": "Mit M oder Esc jederzeit zurueck",
        "score_label": "Punkte {value}",
        "timer_label": "Zeit {value}",
        "speed_label": "Tempo {value}",
        "difficulty_easy_label": "Leicht",
        "difficulty_normal_label": "Normal",
        "difficulty_hard_label": "Schwer",
        "difficulty_value": "Schwierigkeit {value}",
        "badge_ai": "KI",
        "badge_phase": "Phase {value}",
        "badge_slow": "Langsam {value}",
        "badge_haste": "Tempo {value}",
        "badge_bounce": "Prall {value}",
        "badge_magnet": "Magnet {value}",
        "badge_out": "Raus",
        "food_apple": "Apfel",
        "food_gold": "Goldfrucht",
        "food_phase": "Phasenfrucht",
        "food_freeze": "Frostfrucht",
        "food_haste": "Tempofrucht",
        "food_bounce": "Prallfrucht",
        "food_magnet": "Magnetfrucht",
        "mode_timed_solo_label": "Zeitlauf Solo",
        "mode_timed_solo_desc": "Ein Solomodus mit frei waehlbarer Spielzeit.",
        "mode_versus_ai_label": "Mensch gegen KI",
        "mode_versus_ai_desc": "Spiele direkt gegen eine KI.",
        "mode_local_duel_label": "Lokales Duell",
        "mode_local_duel_desc": "Zwei Spieler lokal an einer Tastatur.",
        "mode_coop_label": "Koop-Lauf",
        "mode_coop_desc": "Lokaler Koop mit gemeinsamer Zeitvorgabe.",
        "mode_lan_host_label": "LAN Host",
        "mode_lan_host_desc": "LAN-Raum erstellen und auf den Client warten.",
        "mode_lan_join_label": "LAN Join",
        "mode_lan_join_desc": "Per IP oder Erkennung einem LAN-Raum beitreten.",
        "mode_lan_duel_label": "LAN-Duell",
        "mode_rhythm_mode_label": "Rhythmusmodus",
        "mode_rhythm_mode_desc": "Bewege die Schlange im Beat und baue Combos auf.",
        "mode_strategy_mode_label": "Strategiemodus",
        "mode_strategy_mode_desc": "Mit Skillpunkten, Events und taktischer KI spielen.",
        "msg_choose_mode": "Waehle einen Modus und oeffne die Einstellungen.",
        "msg_collect": "Futter sammeln und Waende sowie eigenen Schwanz meiden.",
        "msg_hosting": "Raum erstellt auf {ip}:{port}",
        "msg_host_failed": "Host fehlgeschlagen: {error}",
        "msg_join_input": "Host-IP eingeben oder einen gefundenen Raum waehlen.",
        "msg_connected_wait": "Verbunden. Warte auf den Start des Hosts.",
        "msg_connect_failed": "Verbindung fehlgeschlagen: {error}",
        "msg_paused": "Pausiert.",
        "msg_resume": "Weiter geht's.",
        "msg_remote_lost": "Verbindung verloren. Rueckkehr ins Menue.",
        "msg_remote_joined": "Spieler verbunden. Match gestartet.",
        "msg_disconnected": "Vom Host getrennt. Esc kehrt zurueck.",
        "msg_food_captured": "{name} hat {food} aufgenommen.",
        "msg_haste_used": "{name} hat Tempoboost erhalten.",
        "msg_freeze_used": "{name} hat das Feld verlangsamt.",
        "msg_bounce_ready": "{name} kann jetzt an Waenden abprallen.",
        "msg_bounce_used": "{name} ist an einer Wand abgeprallt.",
        "msg_magnet_used": "{name} hat Magnetzug erhalten.",
        "msg_magnet_pull": "{name} hat {food} per Magnet angezogen.",
        "msg_food_vanished": "{food} ist verschwunden.",
        "msg_obstacles": "Neue Hindernisse sind erschienen.",
        "game_over": "Spiel vorbei",
        "game_over_score": "Endpunktzahl: {score}",
        "retry_hint": "Enter oder Leertaste fuer einen neuen Versuch.",
        "menu_hint": "Mit M ins Menue.",
        "mission_cleared": "Mission geschafft",
        "mission_score": "Teamwert erreicht {score}.",
        "mission_team": "Die Koop-Runde ist abgeschlossen.",
        "mission_failed": "Mission fehlgeschlagen",
        "mission_failed_score": "Teamwert: {score}",
        "mission_failed_tip": "Versucht bessere Abstimmung und Timing.",
        "winner_title": "{name} gewinnt",
        "winner_score": "{name} endet mit {score} Punkten.",
        "opponent_score": "Gegnerpunkte: {score}",
        "restart_mode": "Enter oder Leertaste startet neu.",
        "result_reason": "Grund: {reason}",
        "reason_wall": "Gegen eine Wand geprallt",
        "reason_obstacle": "Ein Hindernis getroffen",
        "reason_self": "In den eigenen Schwanz gebissen",
        "reason_head_on": "Frontalzusammenstoss",
        "reason_other": "Mit {name} kollidiert",
        "reason_score_target": "Das Ziel zuerst erreicht",
        "reason_last_alive": "Als letzte Schlange ueberlebt",
        "reason_timer_end": "Die Zeit ist abgelaufen",
        "reason_team_failed": "Das Team hat das Ziel nicht rechtzeitig erreicht",
        "result_play_again": "Weiter spielen",
        "result_change_mode": "Modus wechseln",
        "result_quit": "Spiel beenden",
    },
}


class Localizer:
    """Look up translated UI text."""

    def __init__(self, language: str = "zh") -> None:
        self.language = language if language in TRANSLATIONS else "en"

    def set_language(self, language: str) -> None:
        if language in TRANSLATIONS:
            self.language = language

    def get_language_name(self, code: str) -> str:
        return TRANSLATIONS.get(code, TRANSLATIONS["en"]).get("lang_name", code)

    def t(self, key: str, **kwargs) -> str:
        bundle = TRANSLATIONS.get(self.language, TRANSLATIONS["en"])
        text = bundle.get(key) or TRANSLATIONS["en"].get(key, key)
        return text.format(**kwargs)
